defaults: &defaults
  app_name: "rails-freshman"
  domain: "http://rails-freshman.dev"    
  facebook_app_id: '848820491798251'
  facebook_secret: 'e6c2a48616538873f8d9bc5e4ecc322b' 
  hipchat_token: 
  hipchat_room_name: 
  admin_emails: 
    - ""
  google_analytics_key: ""
  default_logo_url: "/logo.png"
  email_sender: ""

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
